version: 2.0
jobs:
  create-tf-user-and-role-dev:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker:1.32
        auth:
          username: $DOCKER_USER
          password: $QUAY_TOKEN

    steps:
      - checkout
      - run:
          command: bundle install
      - run:
          command: mkdir ~/.aws
      - run:
          command: |
            cat <<EOF > ~/.aws/credentials
            [default]
            aws_access_key_id=$AWS_ACCESS_KEY_ID
            aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
            EOF
      - run:
          command: |
            cat <<EOF > ~/sub-account.tfvars
            {
            "bootstrap-aws-default-region" : "us-east-1",
            "sub_account_account_id" : "$DEV_ACCOUNT_ID",
            "sub_account_access_key" : "$DEV_ACCESS_KEY",
            "sub_account_secret_key" : "$DEV_SECRET_KEY"
            }
            EOF
      - run:
          command: terraform init -var-file=~/sub-account.tfvars -backend-config $CIRCLE_WORKING_DIRECTORY/backend.conf
      - run:
          command: terraform apply -var-file=~/sub-account.tfvars
      - run:
          command: terraform plan -var-file=~/sub-account.tfvars

      - run:
          command: bundle exec rspec spec

      - persist_to_workspace:
         root: .
         paths:
           - backend.conf


  destroy:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker:1.20
        auth:
          username: $DOCKER_USER
          password: $QUAY_TOKEN
    steps:
      - checkout
      - run:
          command: mkdir ~/.aws
      - run:
          command: |
            cat <<EOF > ~/.aws/credentials
            [default]
            aws_access_key_id=$AWS_ACCESS_KEY_ID
            aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
            EOF
      - run:
          command: terraform init -var-file=~/sub-account.tfvars -backend-config $CIRCLE_WORKING_DIRECTORY/backend.conf
      - attach_workspace:
          at: /
      - run:
          command:  terraform destroy -var-file=~/sub-account.tfvars -force


workflows:
  version: 2
  terraform-user_wf:
    jobs:
      - create-tf-user-and-role-dev
      - aprove-destroy:
         type: approval
         requires:
           -  create-tf-user-and-role-dev
      - destroy:
          requires:
            - aprove-destroy
