version: 2.0
jobs:
  create-tf-user-and-role:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker:1.20
        auth:
          username: $DOCKER_USER
          password: $QUAY_TOKEN

    steps:
      - checkout
      - run:
          command: bundle install
      - run:
          command: mkdir ~/.aws
      - run:
          command: |
            cat <<EOF > ~/.aws/credentials
            [default]
            aws_access_key_id=$AWS_ACCESS_KEY_ID
            aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
            EOF

      - run:
          command: /terraform init -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars -backend-config $CIRCLE_WORKING_DIRECTORY/backend.conf
      - run:

          command: /terraform apply -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars
      - run:
          command: /terraform plan -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars

      - run:
          command: bundle exec rspec spec

      - persist_to_workspace:
         root: .
         paths:
           - backend.conf


  destroy:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker:1.20
        auth:
          username: $DOCKER_USER
          password: $QUAY_TOKEN
    steps:
      - checkout
      - run:
          command: mkdir ~/.aws
      - run:
          command: |
            cat <<EOF > ~/.aws/credentials
            [default]
            aws_access_key_id=$AWS_ACCESS_KEY_ID
            aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
            EOF
      - run:
          command: /terraform init -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars -backend-config $CIRCLE_WORKING_DIRECTORY/backend.conf
      - attach_workspace:
          at: /
      - run:
          command:  /terraform destroy -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars -force


workflows:
  version: 2
  terraform-user_wf:
    jobs:
      - create-tf-user-and-role
      - aprove-destroy:
         type: approval
         requires:
           -  create-tf-user-and-role
      - destroy:
          requires:
            - aprove-destroy
