version: 2.0
jobs:
  build-deploy-test-ami:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker:1.20
        auth:
          username: $DOCKER_USER
          password: $QUAY_TOKEN

    steps:
      - checkout
      - run:
          command: bundle install
      - run:
          command: mkdir ~/.aws
      - run:
          command: |
            cat <<EOF > ~/.aws/credentials
            [default]
            aws_access_key_id=$AWS_ACCESS_KEY_ID
            aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
            EOF

      - run:
          command: /terraform init -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars -backend-config $CIRCLE_WORKING_DIRECTORY/backend.conf
      - run:

          command: /terraform apply -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars
      - run:
          command: /terraform plan -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars

      - run:
          command: bundle exec rspec spec

      - persist_to_workspace:
         root: .
         paths:
           - backend.conf


  destroy:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker:1.20
        auth:
          username: $DOCKER_USER
          password: $QUAY_TOKEN
    steps:
      - attach_workspace:
          at: /
      - run:
          command:  /terraform destroy -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars -force


workflows:
  version: 2
  build-and-deploy-ami:
    jobs:
      - aprove-build:
         type: approval
      - build-deploy-test-ami:
         requires:
           - aprove-build
      - aprove-destroy:
         type: approval
         requires:
           -  build-deploy-test-ami
      - destroy:
          requires:
            - aprove-destroy
