version: 2.0
jobs:
  build:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker:1.17
        auth:
          username: $DOCKER_USER
          password: $QUAY_TOKEN

    steps:
      - checkout
      - run:
          command: /terraform init -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars -backend-config $CIRCLE_WORKING_DIRECTORY/backend.conf
      - run:

          command: /terraform apply -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars
      - run:
          command: /terraform plan -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars
      - run:
          command:  /terraform destroy -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars -force
