version: 2.0
jobs:
  build:
    machine: true

    steps:
      - run:
          name: build
          command: echo helloworld
      - run:
          command: wget https://releases.hashicorp.com/terraform/0.10.1/terraform_0.10.1_linux_amd64.zip
      - run:
          command: unzip terraform_0.10.1_linux_amd64.zip
