version: 2.0
jobs:
  checkout_base_image:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker:1.20
        auth:
          username: $DOCKER_USER
          password: $QUAY_TOKEN

    steps:
      - checkout

  bundle_dependencies:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker:1.20
    steps:
      - run:
          command: bundle install
      - run:
          command: mkdir ~/.aws
      - run:
          command: |
            cat <<EOF > ~/.aws/credentials
            [default]
            aws_access_key_id=$AWS_ACCESS_KEY_ID
            aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
            EOF

  deploy_to_aws:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker:1.20
    steps:
      - run:
          command: /terraform init -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars -backend-config $CIRCLE_WORKING_DIRECTORY/backend.conf
      - run:

          command: /terraform apply -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars
      - run:
          command: /terraform plan -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars

  run_acceptance_test:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker:1.20
    steps:
      - run:
          command: bundle exec rspec spec

  destroy:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker:1.20
    steps:
      - run:
          command:  /terraform destroy -var-file=$CIRCLE_WORKING_DIRECTORY/bootstrap.tfvars -force


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_base_image
      - bundle_dependencies:
          requires:
            - checkout_base_image
      - deploy_to_aws:
          requires:
            - bundle_dependencies
      - run_acceptance_test:
          requires:
            - deploy_to_aws
      - hold:
         type: approval
         requires:
           - run_acceptance_test
      - destroy:
          requires:
            - hold
